import { Playfair_Display } from "next/font/google";
import "./globals.css";
import { HeroSection } from "@/components/HeroSection";
import { Footer } from "@/components/Footer";

const playFairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
});

export const metadata = {
  title: "Johan Philip",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta property="twitter:image" content="og/og.png"></meta>
        <meta property="twitter:card" content="og/og.png"></meta>
        <meta property="twitter:title" content="Johan Philip"></meta>
        <meta
          property="twitter:description"
          content="Software Engineer, Drummer and an Avid Sports Fanatic"
        ></meta>
        <meta property="og:image" content="og/og.png"></meta>
        <meta property="og:title" content="Johan Philip"></meta>
        <meta
          property="og:description"
          content="Software Engineer, Drummer and an Avid Sports Fanatic"
        ></meta>
      </head>
      <body
        className={`${playFairDisplay.variable} font-sans flex flex-col min-h-screen w-screen items-center justify-center dark:bg-black antialiased`}
      >
        <div className="max-w-[900px] w-full py-10">
          <HeroSection />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
